#version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - backend
      - db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/appdb
    depends_on:
      - db
    networks:
      - app-network  
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
